"""
Tools module for Agentic KG.

Contains tool functions used by agents for various tasks.
"""

from .common import tool_success, tool_error, get_state_value, set_state_value
from .user_intent import (
    set_perceived_user_goal,
    approve_perceived_user_goal,
    get_approved_user_goal,
    PERCEIVED_USER_GOAL,
    APPROVED_USER_GOAL,
)
from .file_suggestion import (
    list_available_files,
    sample_file,
    search_file,
    set_suggested_files,
    get_suggested_files,
    approve_suggested_files,
    get_approved_files,
    ALL_AVAILABLE_FILES,
    SUGGESTED_FILES,
    APPROVED_FILES,
)
from .kg_construction import (
    create_uniqueness_constraint,
    load_nodes_from_csv,
    import_nodes,
    import_relationships,
    construct_domain_graph,
    propose_node_construction,
    propose_relationship_construction,
    remove_node_construction,
    remove_relationship_construction,
    get_proposed_construction_plan,
    approve_proposed_construction_plan,
    PROPOSED_CONSTRUCTION_PLAN,
    APPROVED_CONSTRUCTION_PLAN,
)
from .data_preprocessing import (
    # Format analysis
    analyze_data_format,
    analyze_survey_format,
    classify_columns,
    # Wide format transformation
    transform_wide_to_long,
    # Survey format tools
    normalize_values,
    split_multi_value_column,
    extract_entities,
    extract_ratings,
    extract_opinion_pairs,
    parse_survey_responses,
    # State management
    get_transformed_files,
    approve_preprocessing,
    # State keys
    DATA_FORMAT_ANALYSIS,
    TRANSFORMED_FILES,
    SURVEY_FORMAT_ANALYSIS,
    COLUMN_CLASSIFICATION,
    EXTRACTED_ENTITIES,
    EXTRACTED_RATINGS,
    EXTRACTED_OPINIONS,
    SPLIT_MULTI_VALUES,
    NORMALIZED_FILES,
)
from .unstructured_extraction import (
    # NER tools
    get_well_known_types,
    set_proposed_entities,
    get_proposed_entities,
    approve_proposed_entities,
    get_approved_entities,
    # Fact Type tools
    add_proposed_fact,
    get_proposed_facts,
    remove_proposed_fact,
    approve_proposed_facts,
    get_approved_facts,
    # State keys
    PROPOSED_ENTITIES,
    APPROVED_ENTITIES,
    PROPOSED_FACTS,
    APPROVED_FACTS,
)
from .cypher_validation import (
    # Cypher query validation tools
    get_graph_schema_for_cypher,
    propose_cypher_query,
    validate_cypher_syntax,
    execute_and_validate_query,
    get_cypher_feedback,
    approve_cypher_query,
    get_sample_data,
    # State keys
    PROPOSED_CYPHER,
    VALIDATED_CYPHER,
    CYPHER_FEEDBACK,
    QUERY_RESULT,
)
from .schema_design import (
    # Schema design tools
    sample_raw_file_structure,
    detect_potential_entities,
    propose_node_type,
    propose_relationship_type,
    remove_node_type,
    remove_relationship_type,
    get_target_schema,
    get_schema_design_feedback,
    approve_target_schema,
    get_approved_target_schema,
    update_node_extraction_hints,
    update_relationship_extraction_hints,
    get_schema_revision_reason,
    standardize_column_names,
    SCHEMA_DESIGN_FEEDBACK_KEY,
    SCHEMA_REVISION_REASON_KEY,
    COLUMN_STANDARDIZATION_KEY,
    STANDARDIZED_FILE_KEY,
)
from ..models.target_schema import (
    TARGET_SCHEMA_KEY,
    APPROVED_TARGET_SCHEMA_KEY,
    DETECTED_ENTITIES_KEY,
)
from .targeted_preprocessing import (
    get_schema_extraction_plan,
    extract_entities_for_node,
    extract_relationship_data,
    save_extracted_data,
    get_extraction_summary,
    complete_targeted_preprocessing,
    generate_construction_rules,
    get_preprocessing_feedback,
    request_schema_revision,
    TARGETED_EXTRACTION_RESULTS,
    TARGETED_ENTITY_MAPS,
    TARGETED_RELATIONSHIP_DATA,
    TARGETED_PREPROCESSING_COMPLETE,
    GENERATED_FILES,
    PREPROCESSING_FEEDBACK_KEY,
    NEEDS_SCHEMA_REVISION,
    SCHEMA_REVISION_REASON,
)
from .data_cleaning import (
    analyze_file_quality,
    clean_file,
    get_cleaned_files,
    approve_data_cleaning,
    detect_column_types,
    detect_anomalies,
    convert_column_values,
    clean_urls,
    DATA_CLEANING_ANALYSIS_KEY,
    CLEANED_FILES_KEY,
    DATA_CLEANING_COMPLETE_KEY,
)
from .kg_extraction import (
    # Schema tools
    build_entity_schema,
    get_entity_schema,
    # Extraction tools (simplified mode)
    extract_entities_from_text,
    process_unstructured_file,
    get_extraction_results,
    # Extraction tools (GraphRAG mode)
    process_unstructured_file_graphrag,
    process_unstructured_file_auto,
    is_graphrag_available,
    # GraphRAG components
    RegexTextSplitter,
    MarkdownDataLoader,
    make_kg_builder,
    get_graphrag_llm,
    get_graphrag_embedder,
    DashScopeEmbedderAdapter,
    create_contextualized_prompt,
    # Entity resolution tools (simplified mode)
    correlate_entities,
    get_correlation_results,
    create_correspondence_relationships,
    # Entity resolution tools (GraphRAG mode)
    correlate_entities_graphrag,
    auto_correlate_all_entities,
    # State keys
    ENTITY_SCHEMA,
    EXTRACTION_RESULTS,
    CORRELATION_RESULTS,
)

__all__ = [
    # Common
    "tool_success",
    "tool_error",
    "get_state_value",
    "set_state_value",
    # User Intent
    "set_perceived_user_goal",
    "approve_perceived_user_goal",
    "get_approved_user_goal",
    "PERCEIVED_USER_GOAL",
    "APPROVED_USER_GOAL",
    # File Suggestion
    "list_available_files",
    "sample_file",
    "search_file",
    "set_suggested_files",
    "get_suggested_files",
    "approve_suggested_files",
    "get_approved_files",
    "ALL_AVAILABLE_FILES",
    "SUGGESTED_FILES",
    "APPROVED_FILES",
    # KG Construction
    "create_uniqueness_constraint",
    "load_nodes_from_csv",
    "import_nodes",
    "import_relationships",
    "construct_domain_graph",
    "propose_node_construction",
    "propose_relationship_construction",
    "remove_node_construction",
    "remove_relationship_construction",
    "get_proposed_construction_plan",
    "approve_proposed_construction_plan",
    "PROPOSED_CONSTRUCTION_PLAN",
    "APPROVED_CONSTRUCTION_PLAN",
    # Data Preprocessing
    "analyze_data_format",
    "analyze_survey_format",
    "classify_columns",
    "transform_wide_to_long",
    "normalize_values",
    "split_multi_value_column",
    "extract_entities",
    "extract_ratings",
    "extract_opinion_pairs",
    "parse_survey_responses",
    "get_transformed_files",
    "approve_preprocessing",
    "DATA_FORMAT_ANALYSIS",
    "TRANSFORMED_FILES",
    "SURVEY_FORMAT_ANALYSIS",
    "COLUMN_CLASSIFICATION",
    "EXTRACTED_ENTITIES",
    "EXTRACTED_RATINGS",
    "EXTRACTED_OPINIONS",
    "SPLIT_MULTI_VALUES",
    "NORMALIZED_FILES",
    # Unstructured Extraction - NER
    "get_well_known_types",
    "set_proposed_entities",
    "get_proposed_entities",
    "approve_proposed_entities",
    "get_approved_entities",
    "PROPOSED_ENTITIES",
    "APPROVED_ENTITIES",
    # Unstructured Extraction - Fact Types
    "add_proposed_fact",
    "get_proposed_facts",
    "remove_proposed_fact",
    "approve_proposed_facts",
    "get_approved_facts",
    "PROPOSED_FACTS",
    "APPROVED_FACTS",
    # KG Extraction - Schema
    "build_entity_schema",
    "get_entity_schema",
    # KG Extraction - Simplified mode
    "extract_entities_from_text",
    "process_unstructured_file",
    "get_extraction_results",
    # KG Extraction - GraphRAG mode
    "process_unstructured_file_graphrag",
    "process_unstructured_file_auto",
    "is_graphrag_available",
    # KG Extraction - GraphRAG components
    "RegexTextSplitter",
    "MarkdownDataLoader",
    "make_kg_builder",
    "get_graphrag_llm",
    "get_graphrag_embedder",
    "create_contextualized_prompt",
    # KG Extraction - Entity resolution (simplified)
    "correlate_entities",
    "get_correlation_results",
    "create_correspondence_relationships",
    # KG Extraction - Entity resolution (GraphRAG)
    "correlate_entities_graphrag",
    "auto_correlate_all_entities",
    # KG Extraction - State keys
    "ENTITY_SCHEMA",
    "EXTRACTION_RESULTS",
    "CORRELATION_RESULTS",
    # Cypher Validation
    "get_graph_schema_for_cypher",
    "propose_cypher_query",
    "validate_cypher_syntax",
    "execute_and_validate_query",
    "get_cypher_feedback",
    "approve_cypher_query",
    "get_sample_data",
    "PROPOSED_CYPHER",
    "VALIDATED_CYPHER",
    "CYPHER_FEEDBACK",
    "QUERY_RESULT",
    # Schema Design
    "sample_raw_file_structure",
    "detect_potential_entities",
    "propose_node_type",
    "propose_relationship_type",
    "remove_node_type",
    "remove_relationship_type",
    "get_target_schema",
    "get_schema_design_feedback",
    "approve_target_schema",
    "get_approved_target_schema",
    "update_node_extraction_hints",
    "update_relationship_extraction_hints",
    "get_schema_revision_reason",
    "standardize_column_names",
    "TARGET_SCHEMA_KEY",
    "APPROVED_TARGET_SCHEMA_KEY",
    "DETECTED_ENTITIES_KEY",
    "SCHEMA_DESIGN_FEEDBACK_KEY",
    "SCHEMA_REVISION_REASON_KEY",
    "COLUMN_STANDARDIZATION_KEY",
    "STANDARDIZED_FILE_KEY",
    # Targeted Preprocessing
    "get_schema_extraction_plan",
    "extract_entities_for_node",
    "extract_relationship_data",
    "save_extracted_data",
    "get_extraction_summary",
    "complete_targeted_preprocessing",
    "generate_construction_rules",
    "get_preprocessing_feedback",
    "request_schema_revision",
    "TARGETED_EXTRACTION_RESULTS",
    "TARGETED_ENTITY_MAPS",
    "TARGETED_RELATIONSHIP_DATA",
    "TARGETED_PREPROCESSING_COMPLETE",
    "GENERATED_FILES",
    "PREPROCESSING_FEEDBACK_KEY",
    "NEEDS_SCHEMA_REVISION",
    "SCHEMA_REVISION_REASON",
    # Data Cleaning
    "analyze_file_quality",
    "clean_file",
    "get_cleaned_files",
    "approve_data_cleaning",
    "detect_column_types",
    "detect_anomalies",
    "convert_column_values",
    "clean_urls",
    "DATA_CLEANING_ANALYSIS_KEY",
    "CLEANED_FILES_KEY",
    "DATA_CLEANING_COMPLETE_KEY",
]
